### ISSUE TITLE
Citing this package

### ISSUE THREAD

**Issue by RichardLitt** [ProjectBabbler/ebird-api#24]
I used this in my research. How would you like me to cite it?

**Comment by RichardLitt** [comment]
I'd be happy to PR a Citation.cff file, if needed. https://citation-file-format.github.io/cff-initializer-javascript/#/

**Comment by StuartMacKay** [comment]
Richard, sincere apologies for not replying sooner, I only saw this now. I added a citation file, using https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md as a reference. The bumpversion configuration also needed to updated to add the new file also. Let me know if this has everything you need.

**Comment by RichardLitt** [comment]
No worries! Sounds good. Thanks for adding that. All set, happy to cite this.
